image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]

stages:
  - build
  - test

variables:
  OPENQL_STABLE_TAG: "0.5"
  QCODES_STABLE_TAG: "v0.1.11"

before_script:
  - mkdir -p /root/.docker
  - |
    echo "{\"auths\": {
      \"$CI_REGISTRY\": {
        \"username\": \"gitlab-ci-token\",
        \"password\": \"$CI_BUILD_TOKEN\"}
      }
    }" > /root/.docker/config.json
  - cat /root/.docker/config.json
  - export CI_REF=${CI_COMMIT_TAG:-latest}

.docker-base-conda-template:
  stage: build
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/docker/Dockerfile.base_conda
      --destination $CI_REGISTRY_IMAGE/base_conda:$CI_REF

build base conda image:on-schedule:
  extends: .docker-base-conda-template
  only:
    variables:
      # For weekly schedules
      - $SCHEDULE_FREQUENCY == "weekly"
  # kaniko bug https://github.com/GoogleContainerTools/kaniko/issues/245
  allow_failure: true

build base conda image:manual:
  extends: .docker-base-conda-template
  when: manual

.docker-conda-template:
  stage: build
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/docker/Dockerfile.conda
      --destination $CI_REGISTRY_IMAGE/testing_conda:$CI_REF
      --build-arg GITHUB_PULL_USER=$GITHUB_PULL_USER
      --build-arg GITHUB_PULL_TOKEN=$GITHUB_PULL_TOKEN
      --build-arg OPENQL_REVISION=$OPENQL_REVISION
      --build-arg QCODES_REVISION=$QCODES_REVISION

.docker-conda-stable-template:
  extends: .docker-conda-template
  variables:
    OPENQL_REVISION: $OPENQL_STABLE_TAG
    QCODES_REVISION: $QCODES_STABLE_TAG
  # kaniko bug https://github.com/GoogleContainerTools/kaniko/issues/342
  allow_failure: true

.docker-conda-develop-template:
  extends: .docker-conda-template
  variables:
    CI_REF: "develop"
    OPENQL_REVISION: "develop"
    QCODES_REVISION: "master"
  # kaniko bug https://github.com/GoogleContainerTools/kaniko/issues/342
  allow_failure: true

build stable conda image:master:
  extends: .docker-conda-stable-template
  only:
    - master@dicarlolab/pycqed
    - tags

build stable conda image:manual:
  extends: .docker-conda-stable-template
  when: manual

build develop conda image:on-schedule:
  extends: .docker-conda-develop-template
  only:
    # for daily schedules
    - schedules

build develop conda image:manual:
  extends: .docker-conda-develop-template
  when: manual

.run-tests-template:
  stage: test
  image: registry.gitlab.com/dicarlolab/pycqed/base_conda:latest
  variables:
    DISPLAY: ":99"
  before_script:
    - /usr/bin/Xvfb :99 -screen 0 1280x1024x24 &
    - sleep 3
  script:
    # since we have problems with docker image, we will install Qcodes and
    # OpenQL here,
    # BEGIN remove me later
    - mkdir __git_repos__
    - cd __git_repos__
    - git clone "https://$GITHUB_PULL_USER:$GITHUB_PULL_TOKEN@github.com/QE-Lab/OpenQL" openql && \
    - cd openql
    - git checkout $OPENQL_REVISION
    - python setup.py build
    - pip install .
    - cd ../..
    - rm -rf __git_repos__/openql && \
    - pip install --no-cache-dir git+https://github.com/QCoDeS/Qcodes.git@$QCODES_REVISION
    # END remove me later
    - pip install .
    - py.test pycqed/tests --cov=pycqed --cov-report xml --cov-config=.coveragerc
  after_script:
    - killall Xvfb

run tests stable:
  extends: .run-tests-template
  variables:
    OPENQL_REVISION: $OPENQL_STABLE_TAG
    QCODES_REVISION: $QCODES_STABLE_TAG

run tests develop:
  extends: .run-tests-template
  variables:
    OPENQL_REVISION: "develop"
    QCODES_REVISION: "master"
  only:
    # daily
    - schedules
